'''
    Group Privileges Support


    :copyright: (C) 2013 by the SaltStack Team, see AUTHORS for more details.
    :license: Apache 2.0, see LICENSE for more details.


    Revision ID: 101bca597d3a
    Revises: 243bdec8d3fd
    Create Date: 2013-12-19 06:17:31.672034

'''

# revision identifiers, used by Alembic.
revision = '101bca597d3a'
down_revision = '243bdec8d3fd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('name', sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_accounts',
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('account_github_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['account_github_id'], ['accounts.github_id']),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id']),
        sa.PrimaryKeyConstraint()
    )
    op.create_table('group_privileges',
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('privilege_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id']),
        sa.ForeignKeyConstraint(['privilege_id'], ['privileges.id']),
        sa.PrimaryKeyConstraint()
    )


    # Insert Group Privileges data
    privileges = table('privileges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
    )
    # Insert Some Data
    groups = table('groups',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('name', sa.String(length=30), nullable=True),
    )
    group_privileges = table('group_privileges',
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('privilege_id', sa.Integer(), nullable=True),
    )

    # Insert Some Data
    op.bulk_insert(
        privileges, [
            {'name': 'administrator'},
            {'name': 'manager'}
        ]
    )
    op.bulk_insert(
        groups, [
            {'name': 'Administrator'},
            {'name': 'Manager'}
        ]
    )
    op.bulk_insert(
        group_privileges, [
            {'group_id': 1, 'privilege_id': 1},
            {'group_id': 2, 'privilege_id': 2},
        ]
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'privileges')
    op.drop_table('group_privileges')
    op.drop_table('group_accounts')
    op.drop_index('ix_repositories_github_name', 'repositories')
    op.drop_table('repositories')
    op.drop_table('groups')
    ### end Alembic commands ###
