'''
    Add Build Servers


    :copyright: (C) 2013 by the SaltStack Team, see AUTHORS for more details.
    :license: Apache 2.0, see LICENSE for more details.


    Revision ID: 57e879e1f8d6
    Revises: 101bca597d3a
    Create Date: 2013-12-25 23:24:03.577871

'''

# revision identifiers, used by Alembic.
revision = '57e879e1f8d6'
down_revision = '101bca597d3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_servers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(length=256), nullable=False),
        sa.Column('username', sa.String(length=128), nullable=False),
        sa.Column('access_token', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('address')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build_servers')
    ### end Alembic commands ###
