'''
    GitHub Account Support

    Revision ID: 1d780a757476
    Revises: None
    Create Date: 2013-12-18 02:02:02.595940

    :copyright: (C) 2013 by the SaltStack Team, see AUTHORS for more details.
    :license: Apache 2.0, see LICENSE for more details.
'''

# revision identifiers, used by Alembic.
revision = '1d780a757476'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
        sa.Column('github_id', sa.Integer(), nullable=False),
        sa.Column('github_login', sa.String(length=100), nullable=True),
        sa.Column('github_name', sa.String(length=100), nullable=True),
        sa.Column('github_email', sa.String(length=254), nullable=True),
        sa.Column('github_access_token', sa.String(length=100), nullable=True),
        sa.Column('avatar_url', sa.String(length=2000), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('register_date', sa.DateTime(), nullable=True),
        sa.Column('locale', sa.String(length=10), nullable=True),
        sa.Column('timezone', sa.String(length=25), nullable=True),
        sa.PrimaryKeyConstraint('github_id')
    )
    op.create_index('ix_accounts_github_access_token',
                    'accounts',
                    ['github_access_token'],
                    unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_github_access_token', 'accounts')
    op.drop_table('accounts')
    ### end Alembic commands ###
