'''
    Add Builders


    :copyright: (C) 2013 by the SaltStack Team, see AUTHORS for more details.
    :license: Apache 2.0, see LICENSE for more details.


    Revision ID: 3479b5d118be
    Revises: 57e879e1f8d6
    Create Date: 2013-12-27 20:58:24.565288

'''

# revision identifiers, used by Alembic.
revision = '3479b5d118be'
down_revision = '57e879e1f8d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builders',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('display_name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('removed', sa.Boolean(), nullable=False),
        sa.Column('builder_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('builders')
    ### end Alembic commands ###
